version: "3.8"

networks:
  kubenews-network:
    driver: bridge

volumes:
  kubenews_vol:

services:
  postgres:
    image: postgres:latest
    container_name: kubenews-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT_DB:-5432}:5432"
    networks:
      - kubenews-network
    restart: always
    volumes:
      - kubenews_vol:/var/lib/postgresql/data

  api:
    container_name: kubenews-api
    build:
      context: ../src
      dockerfile: ../.devcontainer/Dockerfile
    ports:
      - "${PORT_API_LOCAL:-3333}:${PORT_API_EXPOSE:-3333}"
    restart: always
    depends_on:
      - postgres
    networks:
      - kubenews-network
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_HOST: postgres
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}