version: "3.8"

networks:
  kubenews-network:
    name: kubenews-network
    driver: bridge

volumes:
  kubenews_vol:

services:
  postgres:
    image: postgres
    container_name: kubenews-database
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${PORT_DB}:${PORT_DB}"
    networks:
      - kubenews-network
    restart: always
    volumes:
      - kubenews_vol:/var/lib/postgresql/data

  api:
    container_name: kubenews-api
    build:
      context: ../src
      dockerfile: ../.devcontainer/Dockerfile
    ports:
      - ${PORT_API_LOCAL}:${PORT_API_EXPOSE}
    restart: always
    depends_on:
      - postgres
    networks:
      - kubenews-network