FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache \
    bash \
    python3 \
    make \
    g++ \
    git
COPY package*.json ./
RUN npm install
RUN npm install -g nodemon
COPY . .
USER node
EXPOSE 3333
CMD ["nodemon", "--legacy-watch", "index.js"]